name: Build Artifact
on:
    push:
        branches:
            - master
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            VERSION: 1.0.${{ github.run_id }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: true
            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - run: ./gradlew publish -Pversion=${{ env.VERSION }}
            - name: Upload build artifact
              uses: actions/upload-artifact@v2
              with:
                  path: "build/repo/**/*"

            # Publish Release
            - name: Create ZIP file
              if: startsWith(github.ref, 'refs/tags/')
              run: cd ./build/repo && zip -r ${{ env.GITHUB_WORKSPACE }}/rider-debug-visualizer-web-${{ env.VERSION }}.zip *
            - name: Create Release
              if: startsWith(github.ref, 'refs/tags/')
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
            - name: Upload Release Asset
              if: startsWith(github.ref, 'refs/tags/')
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./rider-debug-visualizer-web-${{ env.VERSION }}.zip
                  asset_name: rider-debug-visualizer-web-${{ env.VERSION }}.zip
                  asset_content_type: application/zip
